<!----------------------------------
****--@name     ${*}
****--@role     ${*}
****--@date     2017/8/9
****--@author   gx
----------------------------------->
<template>
    <div>

    </div>
</template>
<script>
    /*当前组件必要引入*/

    //当前组件引入全局的util
    let Util = null;
    export default{
        props:['getData','url'],
        data() {
            return {


                data:{
                  "criterionId":null,
                  "typeId":1,
                  "teacherType":"IN",
                  "teacherId":1,
                  "teacher":"teacher",
                  "teachType":"PART",
                  "teachTypeId":"10411",
                  "teachTimeRemark":"授课时间，期望的场地、授课时间等要求。",
                  "title":"title测试q",
                  "tags":"tags",
                  "direction":"direction",
                  "logo":"logo",
                  "remark":"remark",
                  "outline":"outline",
                  "auditStatus":"NOT_SUBMIT",
                  "planDtoList":[
                    {
                      "no":1,
                      "duration":1,
                      "content":"content1",
                      "remark":"remark1",
                      "realia":"realia1",
                      "wareDtoList":[
                        {
                          "fileId":2,
                          "title":"课件1",
                          "type":"BEFORE"
                        },
                        {
                          "fileId":2,
                          "title":"课件2",
                          "type":"BEFORE"
                        }
                      ],
                      "testingDtoList":[
                        {
                          "type":"BEFORE",
                          "score":12,
                          "questionsDtoList":[
                            {
                              "types":"RADIO",
                              "subject":"单选题题干",
                              "answer":"A",
                              "answerExplain":"答案解析",
                              "optionsDtoList":[
                                {
                                  "option":"A",
                                  "content":"选项的描述情况"
                                },
                                {
                                  "option":"B",
                                  "content":"选项的描述情况"
                                },
                                {
                                  "option":"C",
                                  "content":"选项的描述情况"
                                }
                              ],
                              "keyWords":null
                            },
                            {
                              "types":"CHECKBOX",
                              "subject":"多选题题干",
                              "answer":"A,C",
                              "answerExplain":"答案解析",
                              "optionsDtoList":[
                                {
                                  "option":"A",
                                  "content":"选项的描述情况"
                                },
                                {
                                  "option":"B",
                                  "content":"选项的描述情况"
                                },
                                {
                                  "option":"C",
                                  "content":"选项的描述情况"
                                }
                              ],
                              "keyWords":null
                            },
                            {
                              "types":"JUDGMENT",
                              "subject":"判断题题干",
                              "answer":"A",
                              "answerExplain":"答案解析",
                              "optionsDtoList":[
                                {
                                  "option":"A",
                                  "content":"正确"
                                },
                                {
                                  "option":"B",
                                  "content":"错误"
                                }
                              ],
                              "keyWords":null
                            },
                            {
                              "types":"ANSWER",
                              "subject":"题干",
                              "answer":"A",
                              "answerExplain":"答案解析",
                              "optionsDtoList":null,
                              "keyWords":[
                                {
                                  "tag":"解剖",
                                  "weight":5
                                },
                                {
                                  "tag":"手术刀",
                                  "weight":3
                                }
                              ]
                            }
                          ]
                        },
                        {
                          "type":"IN_PROGRESS",
                          "score":12,
                          "questionsDtoList":[
                            {
                              "types":"RADIO",
                              "subject":"单选题题干",
                              "answer":"A",
                              "answerExplain":"答案解析",
                              "optionsDtoList":[
                                {
                                  "option":"A",
                                  "content":"选项的描述情况"
                                },
                                {
                                  "option":"B",
                                  "content":"选项的描述情况"
                                },
                                {
                                  "option":"C",
                                  "content":"选项的描述情况"
                                }
                              ],
                              "keyWords":null
                            },
                            {
                              "types":"CHECKBOX",
                              "subject":"多选题题干",
                              "answer":"A,C",
                              "answerExplain":"答案解析",
                              "optionsDtoList":[
                                {
                                  "option":"A",
                                  "content":"选项的描述情况"
                                },
                                {
                                  "option":"B",
                                  "content":"选项的描述情况"
                                },
                                {
                                  "option":"C",
                                  "content":"选项的描述情况"
                                }
                              ],
                              "keyWords":null
                            },
                            {
                              "types":"JUDGMENT",
                              "subject":"判断题题干",
                              "answer":"A",
                              "answerExplain":"答案解析",
                              "optionsDtoList":[
                                {
                                  "option":"A",
                                  "content":"正确"
                                },
                                {
                                  "option":"B",
                                  "content":"错误"
                                }
                              ],
                              "keyWords":null
                            },
                            {
                              "types":"ANSWER",
                              "subject":"题干",
                              "answer":"A",
                              "answerExplain":"答案解析",
                              "optionsDtoList":null,
                              "keyWords":[
                                {
                                  "tag":"解剖",
                                  "weight":5
                                },
                                {
                                  "tag":"手术刀",
                                  "weight":3
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ],
                  "evaluate":{
                    "studentWeight":1,
                    "peersWeight":3,
                    "superiorsWeight":2,
                    "studentEvaluateId":0,
                    "peersEvaluateId":0,
                    "superiorsEvaluateId":0,
                    "studentEvaluate":[
                      {
                        "title":"上课活跃度",
                        "remark":"上课是否活跃",
                        "great":"8",
                        "good":"7",
                        "avg":"5",
                        "bad":"3"
                      },
                      {
                        "title":"上课活跃度",
                        "remark":"上课是否活跃",
                        "great":"8",
                        "good":"7",
                        "avg":"5",
                        "bad":"3"
                      }
                    ],
                    "peersEvaluate":[
                      {
                        "title":"上课活跃度",
                        "remark":"上课是否活跃",
                        "great":"8",
                        "good":"7",
                        "avg":"5",
                        "bad":"3"
                      }
                    ],
                    "superiorsEvaluate":[
                      {
                        "title":"上课活跃度",
                        "remark":"上课是否活跃",
                        "great":"8",
                        "good":"7",
                        "avg":"5",
                        "bad":"3"
                      }
                    ]
                  }
                }

            }
        },
        methods: {
            //初始化请求列表数据
            init(){

            },

        },
        created(){
            this.init();
        },
        mounted(){
        },
        components: {}
    }
</script>
